# Generated by Django 5.2.5 on 2025-11-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovtApplications', '0002_officer_alter_subsidyapplication_decided_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidyapplication',
            name='bill',
            field=models.FileField(default='', upload_to='govt_applications/bills/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidyapplication',
            name='implementation_photo',
            field=models.FileField(default='', upload_to='govt_applications/implementation_photo/'),
            preserve_default=False,
        ),
    ]
