# Generated by Django 5.2.5 on 2025-10-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(unique=True)),
                ('whatsapp_number', models.IntegerField(unique=True)),
                ('service_type', models.TextField(max_length=300)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(max_length=6)),
                ('PAN_Number', models.IntegerField(unique=True)),
                ('GSTIN_Number', models.IntegerField(unique=True)),
            ],
        ),
    ]
