# Generated by Django 5.2.5 on 2025-10-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='GSTIN_Number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='PAN_Number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='district',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='whatsapp_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
