# Generated by Django 5.2.5 on 2025-10-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorRegistration', '0002_alter_vendor_gstin_number_alter_vendor_pan_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='GSTIN_Number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='PAN_Number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
