# Generated by Django 5.2.5 on 2025-10-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorRegistration', '0003_alter_vendor_gstin_number_alter_vendor_pan_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='premium_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
