# Generated by Django 5.2.5 on 2025-08-31 14:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roof_type', models.CharField(choices=[('concrete', 'Concrete Roof'), ('metal', 'Metal Roof'), ('tile', 'Tile Roof'), ('asphalt', 'Asphalt Shingle')], default='concrete', max_length=20)),
                ('runoff_coefficient', models.DecimalField(decimal_places=2, default=0.8, max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)])),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'db_table': 'system_configuration',
            },
        ),
        migrations.CreateModel(
            name='RainfallData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(db_index=True, help_text='Name of the district', max_length=100, unique=True)),
                ('state', models.CharField(blank=True, db_index=True, help_text='State where district is located', max_length=100, null=True)),
                ('country', models.CharField(default='India', help_text='Country where district is located', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this district is active/visible in the system')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Latitude coordinate', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Longitude coordinate', max_digits=11, null=True)),
                ('annual_rainfall_mm', models.DecimalField(decimal_places=2, help_text='Annual rainfall in millimeters', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rainfall Data',
                'verbose_name_plural': 'Rainfall Data',
                'db_table': 'rainfall_data',
                'ordering': ['district_name'],
                'indexes': [models.Index(fields=['district_name', 'state'], name='rainfall_da_distric_578ca3_idx'), models.Index(fields=['state', 'is_active'], name='rainfall_da_state_8811bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roof_length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('roof_width', models.DecimalField(decimal_places=2, max_digits=8)),
                ('roof_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_harvested_liters', models.DecimalField(decimal_places=2, max_digits=12)),
                ('runoff_coefficient', models.DecimalField(decimal_places=2, default=0.8, max_digits=3)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='calculator.rainfalldata')),
            ],
            options={
                'db_table': 'calculation_logs',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['calculated_at'], name='calculation_calcula_a5caef_idx'), models.Index(fields=['district', 'calculated_at'], name='calculation_distric_121c34_idx'), models.Index(fields=['ip_address', 'calculated_at'], name='calculation_ip_addr_4a9068_idx')],
            },
        ),
    ]
