# Generated by Django 5.2.5 on 2025-09-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_calculationlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rainfalldata',
            name='district_name',
            field=models.CharField(db_index=True, help_text='Name of the district', max_length=100),
        ),
    ]
