# Generated by Django 5.2.5 on 2025-09-10 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_rainfalldata_district_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('jan', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('feb', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('mar', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('apr', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('may', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('jun', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('jul', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('aug', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('sep', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('oct', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('nov', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('dec', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Graph Plot',
                'verbose_name_plural': 'Graph Plots',
                'db_table': 'graph_plot',
                'ordering': ['state', 'district_name'],
                'unique_together': {('state', 'district_name')},
            },
        ),
    ]
