# Generated by Django 5.2.5 on 2025-09-10 20:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_graphplot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Calculation Log', 'verbose_name_plural': 'Calculation Logs'},
        ),
        migrations.RemoveIndex(
            model_name='calculationlog',
            name='calculation_calcula_a5caef_idx',
        ),
        migrations.RemoveIndex(
            model_name='calculationlog',
            name='calculation_distric_121c34_idx',
        ),
        migrations.RemoveIndex(
            model_name='calculationlog',
            name='calculation_ip_addr_4a9068_idx',
        ),
        migrations.RenameField(
            model_name='calculationlog',
            old_name='calculated_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='calculationlog',
            name='district',
        ),
        migrations.RemoveField(
            model_name='calculationlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='calculationlog',
            name='roof_area',
        ),
        migrations.RemoveField(
            model_name='calculationlog',
            name='roof_length',
        ),
        migrations.RemoveField(
            model_name='calculationlog',
            name='roof_width',
        ),
        migrations.RemoveField(
            model_name='calculationlog',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='calculationlog',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='calculationlog',
            name='annual_rainfall_mm',
            field=models.FloatField(default=1000, help_text='Annual rainfall in millimeters', validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculationlog',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of client', null=True),
        ),
        migrations.AddField(
            model_name='calculationlog',
            name='district_name',
            field=models.CharField(default=1000, help_text='District name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculationlog',
            name='efficiency_percent',
            field=models.FloatField(blank=True, help_text='System efficiency percentage', null=True),
        ),
        migrations.AddField(
            model_name='calculationlog',
            name='number_of_dwellers',
            field=models.PositiveIntegerField(default=1, help_text='Number of people in household', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculationlog',
            name='roof_area_sqm',
            field=models.FloatField(default=1, help_text='Roof area in square meters', validators=[django.core.validators.MinValueValidator(0.1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculationlog',
            name='roof_type',
            field=models.CharField(default=1, help_text='Type of roof', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculationlog',
            name='state',
            field=models.CharField(blank=True, help_text='State name', max_length=100),
        ),
        migrations.AddField(
            model_name='calculationlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calculationlog',
            name='runoff_coefficient',
            field=models.FloatField(help_text='Runoff coefficient based on roof type', validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='calculationlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the calculation', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calculationlog',
            name='water_harvested_liters',
            field=models.FloatField(help_text='Annual water harvest in liters', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterModelTable(
            name='calculationlog',
            table='calculation_log',
        ),
    ]
