# Generated by Django 5.2.5 on 2025-09-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_calculationlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphplot',
            name='label',
            field=models.CharField(choices=[('RURAL', 'Rural'), ('URBAN', 'Urban'), ('SEMI-URBAN', 'Semi-Urban')], default='URBAN', max_length=20),
        ),
    ]
