# Generated by Django 5.2.5 on 2025-10-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationcache',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
